### ISSUE TITLE
NotificationWorker#default (NoMethodError) "undefined method `comment_url' for #<Notification:0xXXXXXX>"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#246]
<table><tr><th>Exception</th><td>undefined method `comment_url' for #&lt;Notification:0x000000041c0d78&gt;</td></tr><tr><th>Last Occurrence</th><td>March 28, 2013 19:33:21 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.12/lib/active_model/attribute_methods.rb#L407'>/app/vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.12/lib/active_model/attribute_methods.rb:407:in `method_missing'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods.rb#L149'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods.rb:149:in `method_missing'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/decorators/decorators.rb#L11'>/app/app/decorators/decorators.rb:11:in `block (3 levels) in initialize'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/decorators/comment_notification_decorator.rb#L8'>/app/app/decorators/comment_notification_decorator.rb:8:in `twitter_message'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/mailers/notification_direct_message.rb#L3'>/app/app/mailers/notification_direct_message.rb:3:in `comment_direct_message'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/workers/notification_worker.rb#L28'>/app/app/workers/notification_worker.rb:28:in `direct_message'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/workers/notification_worker.rb#L18'>/app/app/workers/notification_worker.rb:18:in `block in perform'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/workers/notification_worker.rb#L17'>/app/app/workers/notification_worker.rb:17:in `each'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/app/workers/notification_worker.rb#L17'>/app/app/workers/notification_worker.rb:17:in `perform'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L45'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:45:in `block (3 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/config/initializers/party_foul_sidekiq.rb#L5'>/app/config/initializers/party_foul_sidekiq.rb:5:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb#L6'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb:6:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb#L49'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb:49:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L11'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb#L22'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb:22:in `with_context'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L7'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:7:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L44'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:44:in `block (2 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L80'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:80:in `stats'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L43'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:43:in `block in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `public_send'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb#L18'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb:18:in `block in initialize'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/9558bbd396e6188784df41a4b4ab8d4289113ff9/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create'</a></pre>

Fingerprint: `602f57064a5d588922e805a0f2ccd5eaa7ba9eb5`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>March 28, 2013 19:33:21 +0000</td></tr><tr><th>Params</th><td><table><tr><th>retry</th><td>false</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>class</th><td>NotificationWorker</td></tr><tr><th>args</th><td>[44]</td></tr><tr><th>at</th><td>1364499185.3286674</td></tr><tr><th>jid</th><td>92b338e9dc6433803b1fb453</td></tr></table></td></tr></table>
