### ISSUE TITLE
EventsController# (NoMethodError) "undefined method `decorated' for #<ActiveRecord::Relation:0x007ffc413d7f80>"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#250]
<table><tr><th>Exception</th><td>undefined method `decorated' for #&lt;ActiveRecord::Relation:0x007ffc413d7f80&gt;</td></tr><tr><th>Last Occurrence</th><td>March 28, 2013 23:13:53 -0400</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.12/lib/active_record/relation/delegation.rb:45:in `method_missing'
<a href='https://github.com/madgloryint/nowplayus/blob/d8418bc5c9fbe12c68e8a2f1ed0c014b8d91fbb3/app/controllers/events_controller.rb#L6'>/Users/erik/Dropbox/Code/nowplayus/app/controllers/events_controller.rb:6:in `index'</a>
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:167:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:426:in `block in _run__2862325053401508571__process_action__1618168732125335951__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_608'
<a href='https://github.com/madgloryint/nowplayus/blob/d8418bc5c9fbe12c68e8a2f1ed0c014b8d91fbb3/app/controllers/application_controller.rb#L22'>/Users/erik/Dropbox/Code/nowplayus/app/controllers/application_controller.rb:22:in `set_time_zone'</a>
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_608'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:425:in `_run__2862325053401508571__process_action__1618168732125335951__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:17:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:121:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:45:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:203:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:246:in `block in action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:36:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:601:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/sass-3.2.7/lib/sass/plugin/rack.rb:54:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb:242:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.12/lib/active_record/query_cache.rb:64:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__92687977720486849__call__2663663710974069949__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:32:in `call_app'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb:22:in `tagged'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb:62:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/engine.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/application.rb:223:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.12/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'</pre>

Fingerprint: `9f2d84497986915ada4e051bd65667b17d14306a`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>March 28, 2013 23:13:53 -0400</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/events</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>events</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>user_id</th><td>19</td></tr><tr><th>flash</th><td>#&lt;ActionDispatch::Flash::FlashHash:0x007ffc3ce7bf40&gt;</td></tr><tr><th>session_id</th><td>0e4b2b7bb2aa8f0a94a558f6b85c9ae5</td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
