### ISSUE TITLE
EventsController# (NameError) "undefined local variable or method `slug' for #<Platform:0xXXXXXX>"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#252]
<table><tr><th>Exception</th><td>undefined local variable or method `slug' for #&lt;Platform:0x00000004d0bc78&gt;</td></tr><tr><th>Last Occurrence</th><td>April 03, 2013 12:10:45 -0400</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace

<pre>/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activemodel-3.2.12/lib/active_model/attribute_methods.rb:407:in `method_missing'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/attribute_methods.rb:149:in `method_missing'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/models/platform.rb#L15'>/home/mubs/Work/madglory/nowplayus/www/app/models/platform.rb:15:in `hashtag'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/models/event.rb#L29'>/home/mubs/Work/madglory/nowplayus/www/app/models/event.rb:29:in `platform_hashtag'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/models/event_tweet.rb#L27'>/home/mubs/Work/madglory/nowplayus/www/app/models/event_tweet.rb:27:in `default_player_status'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/models/event_tweet.rb#L20'>/home/mubs/Work/madglory/nowplayus/www/app/models/event_tweet.rb:20:in `default_status'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__1143925459529325587__initialize__433282588686986592__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_initialize_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/base.rb:500:in `initialize'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/url_for.rb:103:in `initialize'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/views/events/_tweet.html.haml#L6'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_tweet.html.haml:6:in `new'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/views/events/_tweet.html.haml#L6'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_tweet.html.haml:6:in `block in _app_views_events__tweet_html_haml__1059233274503949216_40764060'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:93:in `block in capture_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:345:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:345:in `block in capture_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:569:in `with_haml_buffer'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:341:in `capture_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:93:in `capture_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/helpers/capture_helper.rb:138:in `content_for'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/views/events/_tweet.html.haml#L2'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_tweet.html.haml:2:in `_app_views_events__tweet_html_haml__1059233274503949216_40764060'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:145:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:237:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:41:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:15:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/helpers/rendering_helper.rb:24:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:90:in `non_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/views/events/show.html.haml#L11'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/show.html.haml:11:in `_app_views_events_show_html_haml___1591018886873061883_38632740'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:145:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:18:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:36:in `render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:17:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:110:in `_render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/streaming.rb:225:in `_render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:103:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:88:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:16:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/mubs/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:39:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/controllers/events_controller.rb#L20'>/home/mubs/Work/madglory/nowplayus/www/app/controllers/events_controller.rb:20:in `show'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:167:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:437:in `block in _run__1935663398957433940__process_action__3219408781639315581__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_403'
<a href='https://github.com/madgloryint/nowplayus/blob/694361c3836d447f7e9efc914c39e54320a9bf73/app/controllers/application_controller.rb#L22'>/home/mubs/Work/madglory/nowplayus/www/app/controllers/application_controller.rb:22:in `set_time_zone'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_403'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:425:in `_run__1935663398957433940__process_action__3219408781639315581__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:121:in `process'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:45:in `process'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:203:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:246:in `block in action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:36:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:601:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/sass-3.2.7/lib/sass/plugin/rack.rb:54:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb:242:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/query_cache.rb:64:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__4404400393454165724__call__433282588686986592__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:32:in `call_app'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb:22:in `tagged'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/font_assets-0.1.6/lib/font_assets/middleware.rb:29:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb:62:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/engine.rb:479:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/application.rb:223:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/log_tailer.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'</pre>

Fingerprint: `513b0af57a7d8728aab639d0b71f078e07813b81`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>April 03, 2013 12:07:31 -0400</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/events/32</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>events</td></tr><tr><th>id</th><td>32</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>996af620636f32f057b6e4c9324da9e5</td></tr><tr><th>_csrf_token</th><td>RrzoOvBkub95+oKNzb57LPWcuizA2o4JCXT/3SZFumU=</td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>April 03, 2013 12:10:45 -0400</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/events/32</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>show</td></tr><tr><th>controller</th><td>events</td></tr><tr><th>id</th><td>32</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>996af620636f32f057b6e4c9324da9e5</td></tr><tr><th>_csrf_token</th><td>RrzoOvBkub95+oKNzb57LPWcuizA2o4JCXT/3SZFumU=</td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
