### ISSUE TITLE
EventsController# (SyntaxError) "/home/mubs/Work/madglory/nowplayus/www/app/views/events/_schedule.html.haml:2: syntax error, unexpected ',', expecting ')'
));}</p>\n", 0, false);::Haml::Util.html_...
            ^
/home/mubs/Work/madglory/nowplayus/www/a

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#259]
<table><tr><th>Exception</th><td>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_schedule.html.haml:2: syntax error, unexpected ',', expecting ')'
));}&lt;/p&gt;\n&quot;, 0, false);::Haml::Util.html_...
            ^
/home/mubs/Work/madglory/nowplayus/www/app/views/events/_schedule.html.haml:2: syntax error, unexpected keyword_ensure, expecting '}'
...:Util.html_safe(_erbout);ensure;@haml_buffer = @haml_buffer....
...                               ^
/home/mubs/Work/madglory/nowplayus/www/app/views/events/_schedule.html.haml:2: syntax error, unexpected keyword_end, expecting '}'
...uffer.upper if @haml_buffer;end;
...                               ^
/home/mubs/Work/madglory/nowplayus/www/app/views/events/_schedule.html.haml:5: syntax error, unexpected keyword_end, expecting '}'</td></tr><tr><th>Last Occurrence</th><td>April 05, 2013 19:20:01 -0400</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre>/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:297:in `module_eval'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:297:in `compile'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:244:in `block in compile!'
<internal:prelude>:10:in `synchronize'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:232:in `compile!'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:144:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:237:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:41:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:15:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/helpers/rendering_helper.rb:24:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:90:in `non_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/views/events/_event.html.haml#L3'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_event.html.haml:3:in `_app_views_events__event_html_haml__864168360870607896_70340663791160'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:145:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:237:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:41:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/helpers/rendering_helper.rb:27:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:90:in `non_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/views/events/_upcoming_events.html.haml#L23'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_upcoming_events.html.haml:23:in `block in _app_views_events__upcoming_events_html_haml___4431789353034983633_70340693203200'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/relation/delegation.rb:6:in `each'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/relation/delegation.rb:6:in `each'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/views/events/_upcoming_events.html.haml#L21'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/_upcoming_events.html.haml:21:in `_app_views_events__upcoming_events_html_haml___4431789353034983633_70340693203200'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:145:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/partial_renderer.rb:237:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:41:in `render_partial'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/helpers/rendering_helper.rb:27:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers.rb:90:in `non_haml'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/views/events/index.html.haml#L2'>/home/mubs/Work/madglory/nowplayus/www/app/views/events/index.html.haml:2:in `_app_views_events_index_html_haml___3891757369461153754_38155340'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:145:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:125:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/template.rb:143:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/template_renderer.rb:18:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:36:in `render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_view/renderer/renderer.rb:17:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:110:in `_render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/streaming.rb:225:in `_render_template'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:103:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:88:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:16:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/mubs/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:39:in `render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/controllers/events_controller.rb#L8'>/home/mubs/Work/madglory/nowplayus/www/app/controllers/events_controller.rb:8:in `index'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:167:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:426:in `block in _run__2644136967015651423__process_action__1516717643696424237__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_861'
<a href='https://github.com/madgloryint/nowplayus/blob/6c6447522968a897364726ec79438c10724be317/app/controllers/application_controller.rb#L22'>/home/mubs/Work/madglory/nowplayus/www/app/controllers/application_controller.rb:22:in `set_time_zone'</a>
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_861'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:425:in `_run__2644136967015651423__process_action__1516717643696424237__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `block in instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:121:in `process'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:45:in `process'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:203:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_controller/metal.rb:246:in `block in action'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:36:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:601:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/sass-3.2.7/lib/sass/plugin/rack.rb:54:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb:242:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/query_cache.rb:64:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__2570058944628571615__call__1471148580351993434__callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:32:in `call_app'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `block in call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb:22:in `tagged'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb:62:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/engine.rb:479:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/application.rb:223:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/railties-3.2.12/lib/rails/rack/log_tailer.rb:17:in `call'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
/home/mubs/.rvm/gems/ruby-1.9.3-p374@nowplayus/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'</pre>

Fingerprint: `5755868a91f3e447ae9751aa8d9ec1c250737fb5`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>April 05, 2013 19:20:01 -0400</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/events</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>events</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>user_id</th><td>4</td></tr><tr><th>session_id</th><td>30eb64992ae61992069ba4521ce3e7f2</td></tr><tr><th>_csrf_token</th><td>n/UN7bAvZ39p2kUDGs3S2mnkRrnr+DCXJOWZMWGJDos=</td></tr></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
