### ISSUE TITLE
NotificationWorker#default (NameError) "uninitialized constant Notification::Actionable"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#270]
<table><tr><th>Exception</th><td>uninitialized constant Notification::Actionable</td></tr><tr><th>Last Occurrence</th><td>May 04, 2013 15:47:10 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/inheritance.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/inheritance.rb:111:in `compute_type'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/reflection.rb#L172'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/reflection.rb:172:in `klass'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb#L117'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb:117:in `klass'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/belongs_to_association.rb#L24'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/belongs_to_association.rb:24:in `find_target?'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb#L137'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb:137:in `load_target'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb#L55'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/association.rb:55:in `reload'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/singular_association.rb#L9'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/singular_association.rb:9:in `reader'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/builder/association.rb#L44'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/associations/builder/association.rb:44:in `block in define_readers'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/workers/notification_worker.rb#L11'>/app/app/workers/notification_worker.rb:11:in `perform'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L45'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:45:in `block (3 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/config/initializers/party_foul_sidekiq.rb#L5'>/app/config/initializers/party_foul_sidekiq.rb:5:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb#L6'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb:6:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb#L49'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb:49:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L11'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb#L22'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb:22:in `with_context'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L7'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:7:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L44'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:44:in `block (2 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L80'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:80:in `stats'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L43'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:43:in `block in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `public_send'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb#L18'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb:18:in `block in initialize'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create'</a></pre>

Fingerprint: `51faaf2fc9bdf00bf9f8b4d5367ece19caf0108c`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>May 04, 2013 15:47:10 +0000</td></tr><tr><th>Params</th><td><table><tr><th>retry</th><td>false</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>class</th><td>NotificationWorker</td></tr><tr><th>args</th><td>[228]</td></tr><tr><th>at</th><td>1367682426.2964277</td></tr><tr><th>jid</th><td>c959984d203f6fae03cdf026</td></tr></table></td></tr></table>
