### ISSUE TITLE
ApplicationController# (TypeError) "expected Hash (got String) for param `_REQUEST'"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#277]
<table><tr><th>Exception</th><td>expected Hash (got String) for param `_REQUEST'</td></tr><tr><th>Last Occurrence</th><td>January 07, 2014 06:23:34 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb#L127'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb:127:in `normalize_params'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb#L96'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb:96:in `block in parse_nested_query'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb#L93'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb:93:in `each'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb#L93'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/utils.rb:93:in `parse_nested_query'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb#L332'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb:332:in `parse_query'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/request.rb#L269'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/request.rb:269:in `parse_query'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb#L186'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/request.rb:186:in `GET'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/request.rb#L225'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/request.rb:225:in `GET'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/parameters.rb#L10'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/parameters.rb:10:in `parameters'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/filter_parameters.rb#L33'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/http/filter_parameters.rb:33:in `filtered_parameters'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb#L21'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/instrumentation.rb:21:in `process_action'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/params_wrapper.rb#L207'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb#L18'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/railties/controller_runtime.rb:18:in `process_action'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/base.rb#L121'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:121:in `process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb#L45'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/rendering.rb:45:in `process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal.rb#L203'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal.rb:203:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/rack_delegation.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal.rb#L246'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal.rb:246:in `block in action'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb#L73'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb#L73'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb#L36'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:36:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb#L68'>/app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb#L56'>/app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb#L56'>/app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb#L601'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:601:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb#L177'>/app/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb#L157'>/app/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb#L177'>/app/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb#L157'>/app/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/builder.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/request_store-1.0.5/lib/request_store/middleware.rb#L9'>/app/vendor/bundle/ruby/1.9.1/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sass-3.2.7/lib/sass/plugin/rack.rb#L54'>/app/vendor/bundle/ruby/1.9.1/gems/sass-3.2.7/lib/sass/plugin/rack.rb:54:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/party_foul-1.2.1/lib/party_foul/middleware.rb#L8'>/app/vendor/bundle/ruby/1.9.1/gems/party_foul-1.2.1/lib/party_foul/middleware.rb:8:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb#L17'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb#L25'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb#L21'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb:21:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb#L242'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb:242:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb#L210'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb#L205'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb#L341'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb:341:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/query_cache.rb#L64'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/query_cache.rb:64:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb#L479'>/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb#L28'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb#L405'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__206865903078258099__call__1928407093591363304__callbacks'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb#L405'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb#L385'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb#L81'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb#L27'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb#L31'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb#L16'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb#L56'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb#L32'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:32:in `call_app'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb#L16'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb#L22'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb:22:in `tagged'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb#L16'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb#L22'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb:22:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb#L21'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb#L17'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb#L72'>/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb#L62'>/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb:62:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L136'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L143'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L172'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:172:in `rescue in lookup'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L168'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:168:in `lookup'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L66'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb#L51'>/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb#L479'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:479:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application.rb#L223'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:223:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/content_length.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/log_tailer.rb#L17'>/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/log_tailer.rb:17:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb#L412'>/app/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb:412:in `handle_request'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb#L306'>/app/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb:306:in `process_client'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb#L215'>/app/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/server.rb:215:in `block in run'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/thread_pool.rb#L94'>/app/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/thread_pool.rb#L94'>/app/vendor/bundle/ruby/1.9.1/gems/puma-1.6.3/lib/puma/thread_pool.rb:94:in `block in spawn_thread'</a></pre>

Fingerprint: `7123be667f74e13c68d08f0542e08c1606bbb42a`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>January 07, 2014 06:23:34 +0000</td></tr><tr><th>URL</th><td>[GET] /index.php?_REQUEST=&amp;_REQUEST[option]=com_content&amp;_REQUEST[Itemid]=1&amp;GLOBALS=&amp;mosConfig_absolute_path=http://www.google.com/humans.txt?</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>application</td></tr><tr><th>action</th><td>rescue_404</td></tr><tr><th>a</th><td>index</td></tr><tr><th>format</th><td>php</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>10.165.5.55</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td></td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td></td></tr></table></td></tr></table>
