### ISSUE TITLE
NotificationWorker#default (Twitter::Error::Forbidden) "This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later."

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#278]
<table><tr><th>Exception</th><td>This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later.</td></tr><tr><th>Last Occurrence</th><td>April 04, 2014 19:51:08 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/response/raise_error.rb#L21'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/response/raise_error.rb:21:in `on_complete'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb#L9'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb:9:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb#L63'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb:63:in `on_complete'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb#L8'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/response.rb:8:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/request/url_encoded.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/request/url_encoded.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/request/multipart.rb#L13'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/request/multipart.rb:13:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/request/multipart_with_file.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/request/multipart_with_file.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/connection.rb#L247'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/connection.rb:247:in `run_request'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/connection.rb#L112'>/app/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.6/lib/faraday/connection.rb:112:in `post'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/client.rb#L81'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/client.rb:81:in `request'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/client.rb#L70'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/client.rb:70:in `post'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/api/utils.rb#L82'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/api/utils.rb:82:in `object_from_response'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/api/direct_messages.rb#L141'>/app/vendor/bundle/ruby/1.9.1/gems/twitter-4.5.0/lib/twitter/api/direct_messages.rb:141:in `direct_message_create'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/models/direct_message.rb#L23'>/app/app/models/direct_message.rb:23:in `deliver'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/workers/notification_worker.rb#L28'>/app/app/workers/notification_worker.rb:28:in `direct_message'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/workers/notification_worker.rb#L18'>/app/app/workers/notification_worker.rb:18:in `block in perform'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/workers/notification_worker.rb#L17'>/app/app/workers/notification_worker.rb:17:in `each'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/app/workers/notification_worker.rb#L17'>/app/app/workers/notification_worker.rb:17:in `perform'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L45'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:45:in `block (3 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L109'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:109:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/config/initializers/party_foul_sidekiq.rb#L5'>/app/config/initializers/party_foul_sidekiq.rb:5:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb#L14'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/timeout.rb:14:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb#L6'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/active_record.rb:6:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb#L49'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/retry_jobs.rb:49:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L11'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb#L22'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/logging.rb:22:in `with_context'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb#L7'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/server/logging.rb:7:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L111'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb#L114'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/middleware/chain.rb:114:in `invoke'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L44'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:44:in `block (2 levels) in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L80'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:80:in `stats'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb#L43'>/app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.7.5/lib/sidekiq/processor.rb:43:in `block in process'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `public_send'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb#L23'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `dispatch'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb#L18'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb:18:in `block in initialize'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call'</a>
<a href='https://github.com/madgloryint/nowplayus/blob/73e2f126589b974c3fdc16b84a00ec5af6a88baa/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb#L48'>/app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create'</a></pre>

Fingerprint: `00532efe75472ef49a5bbac58bb603ad57100bc1`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>April 04, 2014 19:51:08 +0000</td></tr><tr><th>Params</th><td><table><tr><th>retry</th><td>false</td></tr><tr><th>queue</th><td>default</td></tr><tr><th>class</th><td>NotificationWorker</td></tr><tr><th>args</th><td>[479]</td></tr><tr><th>at</th><td>1396641059.968011</td></tr><tr><th>jid</th><td>9709e33f5f0de22db9e4db38</td></tr></table></td></tr></table>
