### ISSUE TITLE
# (Exception) "LIKE WOAH!"

### ISSUE THREAD

**Issue by CL4P-TP** [madglory/nowplayus#9]
<table><tr><th>Exception</th><td>LIKE WOAH!</td></tr><tr><th>Last Occurrence</th><td>February 14, 2013 15:23:19 -0500</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/madgloryint/nowplayus/blob/b6238be048273b30f1d908b3e092e3053d971bb3/app/controllers/home_controller.rb#L5'>/Users/erik/Dropbox/Code/nowplayus/app/controllers/home_controller.rb:5:in `index'</a>
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:414:in `_run__704875401313567944__process_action__719603627545876062__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:203:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in action'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/etag.rb:23:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/conditionalget.rb:25:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:210:in `context'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:205:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__4356627805400205208__call__3655298496646967535__callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/methodoverride.rb:21:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/runtime.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/lock.rb:15:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/application.rb:223:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/content_length.rb:14:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/local/opt/rbenv/versions/1.9.3-p327/gemsets/nowplayus/gems/rack-1.4.3/lib/rack/handler/webrick.rb:59:in `service'
/usr/local/opt/rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/usr/local/opt/rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/usr/local/opt/rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'</pre>

Fingerprint: `f7064395934f805309561c0eaa39accff80d1f9c`

**Comment by CL4P-TP** [comment]
<table><tr><th>Occurred At</th><td>February 14, 2013 15:23:19 -0500</td></tr><tr><th>Params</th><td></td></tr></table>
